# Generated by Django 3.1.4 on 2021-01-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200927_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='client',
            field=models.CharField(default='none', max_length=160),
        ),
        migrations.AddField(
            model_name='work',
            name='imageone',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='work',
            name='imagethree',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='work',
            name='imagetwo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='work',
            name='tools',
            field=models.CharField(default='none', max_length=160),
        ),
        migrations.AddField(
            model_name='work',
            name='webtype',
            field=models.CharField(default='none', max_length=160),
        ),
    ]
