# Generated by Django 3.1.4 on 2021-01-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210106_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='sitename',
            field=models.CharField(default='none', max_length=160),
        ),
        migrations.AlterField(
            model_name='work',
            name='client',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
